// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtN9gLjFU0uM7M5JzLv79S4TQA9hfaqJ4',
    appId: '1:224268205736:web:04c2cc69dad633b8688c9d',
    messagingSenderId: '224268205736',
    projectId: 'flutter-deploy-3379b',
    authDomain: 'flutter-deploy-3379b.firebaseapp.com',
    storageBucket: 'flutter-deploy-3379b.appspot.com',
    measurementId: 'G-63CJP9BF84',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCP0CRfhNlK_SuScNu0zsbj796o0AdtAt0',
    appId: '1:224268205736:android:5eb20795b1b600b2688c9d',
    messagingSenderId: '224268205736',
    projectId: 'flutter-deploy-3379b',
    storageBucket: 'flutter-deploy-3379b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByIDTU_JrKBAOWBmHBqEBrMZNUxu3miAw',
    appId: '1:224268205736:ios:b4437e2a6479f2bf688c9d',
    messagingSenderId: '224268205736',
    projectId: 'flutter-deploy-3379b',
    storageBucket: 'flutter-deploy-3379b.appspot.com',
    iosBundleId: 'com.example.examen3',
  );
}
